name: Generate color swatches

on:
  push:
    branches: [main]
    paths:
      - themes/**
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Generate swatches
        uses: andornaut/color-swatches-action@main
        with:
          files: 'themes/*.json'
          out-dir: 'swatches'
          format: 'png'
